//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AreGamersStreaming.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Bootatstartup {
            get {
                return ((bool)(this["Bootatstartup"]));
            }
            set {
                this["Bootatstartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Minamizeatstart {
            get {
                return ((bool)(this["Minamizeatstart"]));
            }
            set {
                this["Minamizeatstart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection StreamList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StreamList"]));
            }
            set {
                this["StreamList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HowOftenToCheck {
            get {
                return ((int)(this["HowOftenToCheck"]));
            }
            set {
                this["HowOftenToCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.twitch.tv/kraken/")]
        public string TwitchAPI {
            get {
                return ((string)(this["TwitchAPI"]));
            }
            set {
                this["TwitchAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Accept: application/vnd.twitchtv.v3+json")]
        public string TwitchJSONHeaderv3 {
            get {
                return ((string)(this["TwitchJSONHeaderv3"]));
            }
            set {
                this["TwitchJSONHeaderv3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Accept: application/vnd.twitchtv.v2+json")]
        public string TwitchJSONHeaderv2 {
            get {
                return ((string)(this["TwitchJSONHeaderv2"]));
            }
            set {
                this["TwitchJSONHeaderv2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.twitch.tv/kraken/streams/")]
        public string TwitchAPIStream {
            get {
                return ((string)(this["TwitchAPIStream"]));
            }
            set {
                this["TwitchAPIStream"] = value;
            }
        }
    }
}
